Restructured the iSAQB Foundation curriculum as agreed in the iSAQB Foundation meeting in January 2024
isaqb-org/curriculum-foundation pull request #391
Opened 2024-02-11 04:01 UTC by rhoadesre

### Overview
Changed all of the learning goal numbers and associated files to restructure the curriculum as agreed in the iSAQB Foundation Meeting in January 2024. There were some open questions in the meeting, so I took my best guess at rearranging some of the learning goals.
Parts of the new structure will make more sense when considering my proposed changes to the curriculum - refer to notes in this comment below the structure. At some point I will take my recommendations and create individual issues for them, but it's almost 5 in the morning, and I'm too tired to create the individual issues tonight. 

### New Structure
**1. Basic Concepts of Software Architecture**
LG 01-01: Discuss Definitions of Software Architecture (R1)
LG 01-02: Understand and Explain the Goals and Benefits of Software Architecture (R1)
LG 01-03 [previously LG 1-04: Understand Software Architects' Tasks and Responsibilities (R1)
LG 01-04 [previously LG 1-09]: Responsibilities of Software Architects within the Greater Architectural Context (R3)
LG 01-05 [previously LG 1-03: Understand Software Architecture as Part of the Software Lifecycle (R2)
	Candidate for deletion
LG 01-06 [previously LG 1-10]: Differentiate Types of IT Systems (R3)
	Candidate for deletion

**2. Software Architecture and Requirements**
LG 02-01 [previously LG 1-05]: Relate the Role of Software Architects to Other Stakeholders (R1)
LG 02-02 [previously LG 2-03]: Identify and Consider Factors Influencing Software Architecture (R1-R3)
LG 02-03 [previously LG 4-03]: Requirements and Software Architecture (R1-R3)
LG 02-04 [previously LG 4-01]: Understand and Explain Software System Qualities (R1)
LG 02-05 [previously LG 1-08]: Distinguish Explicit Statements and Implicit Assumptions (R1)
LG 02-06 [previously LG 1-07]: Differentiate between Short- and Long-Term Goals (R2)
	Candidate for deletion

**3. Design and Development of Software Architecture**
LG 03-01 [previously LG 2-08]: Achieve Quality Requirements with Appropriate Approaches and Techniques (R1)
LG 03-02 [previously LG 4-04]: Improving Qualities through Architecture (R1)
LG 03-03 [previously LG 2-02]: Design Software Architectures (R1)
LG 03-04 [previously LG 2-07]: Manage Dependencies between Building Blocks (R1)
LG 03-05 [previously LG 2-05]: Describe, Explain and Appropriately Apply Important Solution Patterns (R1, R3)
LG 03-06 [previously LG 2-06]: Explain and Use Design Principles (R1-R3)
LG 03-07 [previously LG 2-10]: Know Fundamental Principles of Software Deployment (R3)
LG 03-08 [previously LG 2-04]: Design and Implement Cross-Cutting Concepts (R1)
LG 03-09 [previously LG 2-09]: Design and Define Interfaces (R1-R3)
LG 03-10 [previously LG 1-11]: Challenges of Distributed Systems (R3)
LG 03-11 [previously LG 1-06]: Can Explain the Correlation between Development Approaches and Software Architecture (R2)
LG 03-12 [previously LG 2-01]: Select and Use Approaches and Heuristics for Architecture Development (R1,R3)

**4. Specification and Communication of Software Architecture**
LG 04-01 [previously LG 3-01]: Explain and Consider the Requirements of Technical Documentation (R1)
LG 04-02 [previously LG 3-02]: Describe and Communicate Software Architectures (R1-R3)
LG 04-03 [previously LG 3-03]: Explain and Apply Notations/Models to Describe Software Architecture (R2-R3)
LG 04-04 [previously LG 3-04]: Explain and Use Architectural Views (R1)
LG 04-05 [previously LG 3-05]: Explain and Apply Context View of Systems (R1)
LG 04-06 [previously LG 3-06]: Document and Communicate Cross-Cutting Concepts (R2)
LG 04-07 [previously LG 3-07]: Describe Interfaces (R1)
LG 04-08 [previously LG 3-08]: Explain and Document Architectural Decisions (R1-R2)
LG 04-09 [previously LG 3-09]: Know Additional Resources and Tools for Documentation (R3)

**5. Analysis and Assessment of Software Architecture**
LG 05-01 [previously LG 4-02]: Analyse Software System Qualities (R1-R3)

**6. Examples of Software Architecture**
LG 06-01 [previously LG 5-1]: Know the Relation between Requirements, Constraints, and Solutions (RLG 3)
LG 06-02 [previously LG 5-2]: Know the Rationale of a Solution’s Technical Implem2ntation (R3)

### Open issues to the curriculum, once we agree on the final structure

1. Remove old learning goal names, e.g., "[previously LG 4-03]"
2. References to specific learning goals
3. German and English versions of the curriculum aren't being created, only the English version without the "EN" suffix.
4. Crreate new TOC
5. In case new chapters are added, the duration etc. needs to change.

### Recommended changes to the curriculum

**1. Delete LG "Understand Software Architecture as Part of the Software Lifecycle" or rename and move to chapter 2.**
- If this learning goals should be kept, then change the name to "Understand how Changes to the Influencing Factors have Consequences on the Software Architecture" and move to chapter 2. The content can remain unchanged.
- In my opinion, the content doesn't have much to do with the software lifecycle and this relation only causes confusion, especially in agile environments. 

**2. Delete LG "Differentiate Types of IT Systems"**
- This seems to be a random set of types of systems that also overlap with one another. Why do architects need to differentiate between these types of systems?

**3. Rename Chapter 2 "Software Architecture and Requirements" to "External Factors that Influence Software Architecture"**
- The content of this chapter goes beyond just requirements to include stakeholder concerns (new) and constraints (currently called influencing factors), as well as trends and business and project goals.

**4. Change LG "Relate the Role of Software Architects to Other Stakeholders" and change the focus to "Stakeholder Concerns and their Impact on Software Architecture"**
  - [Note from Roger: Stakeholder concerns aren't addressed concretely in the current curriculum and, in my experience, have a great impact on the architecture, even if they can't be directly translated into requirements.]
  - [Proposed text - depict stakeholders and concerns in a table]
    - Architects can identify stakeholders and their concerns, as well as their impact on the software architecture or the design and development process. 
    - Examples of stakeholders and concerns are as follows:
| Stakeholder | Stakeholder Concern |
| --- | --- |
| product management and product owners | e.g., required time and feasibility for the implementation of the requirements |
| project managers | e.g., required time and budget for the implementation, associated risks of the chosen architectural approach |
| requirement engineers (requirements- or business analysts, requirements managers, system analysts, business owners, subject-matter experts, etc.) | e.g., fulfillment of the requirements, e.g., impact of the system or current processes and daily work activities |
| developers | e.g., components and interfaces to be implemented, protocols, technology constraints |
| quality assurance and testers | e.g., components to be tested |
| IT operators and administrators (applies primarily to production environment or data centers for information systems), hardware developers | e.g., infrastructure requirements required to run the system, backup and archival requirements |
| enterprise architects and architecture board members | e.g., compatibility of the system within the IT landscape, conformity to company-wide guidelines |
  - Architects understand that not all stakeholder concerns can be translated into requirements, but may nevertheless need to be considered.
  - Architects are able to determine the impact of the stakeholder concerns on the architecture or on the design and development process.
  - Architects are able to determine how the architecture should be documented (and perhaps designed) to address the stakeholder concerns.

**5. Rename and restructure LG "Identify and Consider Factors Influencing Software Architecture" to "Identify External Constrai [...]

2024-02-12 05:58 UTC, gernotstarke requested changes
I URGENTLY ask for moving these changes to a new branch instead of proposing to work on main.

(consider using 2025-work or similar as branch name).

The main branch NEEDS TO BE KEPT as-is for eventually required hotfixes.

2024-02-12 09:39 UTC, programming-wolf commented
Change the target of the PR to `curriculum-2025-work`, so that all changes can be merged into _that_ branch.

2024-02-13 08:41 UTC, merged

2024-02-13 08:42 UTC, gernotstarke commented
I merge these changes, so we have a baseline for the upcoming major changes.

2024-02-23 10:39 UTC, mikesperber reviewed
Great stuff - I have a few quibbles with the orderings.

2024-02-23 10:39 UTC, mikesperber commented on docs/02-requirements/LZ-02-01.adoc
I don't see how this fits under "requirements" - shouldn't this move (back) to the "Basic Concepts" section?

2024-02-23 10:39 UTC, mikesperber commented on docs/02-requirements/LZ-02-03.adoc
This should be swapped with the following LG, so it's:

1. "Understand and Explain Software System Qualities"
(which is about terminology around "qualities")
and then
2. Requirements and Software Architecture
(which extends the terminology)

2024-02-23 10:39 UTC, mikesperber commented on docs/02-requirements/LZ-02-05.adoc
This is very basic and fundamental, should be nearer the beginning of the section.

2024-02-23 10:39 UTC, mikesperber commented on docs/02-requirements/LZ-02-06.adoc
This is also very basic and fundamental, should be nearer the beginning of the section.

2024-02-23 10:39 UTC, mikesperber commented on docs/03-design/LZ-03-03.adoc
This explains what the section means by "Design" and thus should be at the beginning of that section.

2024-02-23 10:39 UTC, mikesperber commented on docs/03-design/LZ-03-06.adoc
This should be nearer the beginning - at least before "patterns", as it's more general.  I’d say before everything except for “Design Principles”.