Improve listing of specific metrics
isaqb-org/curriculum-foundation pull request #450
Opened 2024-05-21 18:19 UTC by mikesperber

Addresses #431

2024-06-09 16:00 UTC, mikesperber commented
> I'd prefer the German "eingehende und ausgehende Abhängigkeiten" to the noun-version "Eingangs- und Ausgangs".

Done.

2024-06-10 06:15 UTC, gernotstarke commented
> > I'd prefer the German "eingehende und ausgehende Abhängigkeiten" to the noun-version "Eingangs- und Ausgangs".
> 
> @gernotstarke Done.

@mikesperber you still use the noun. I suggest the following wording:

"Architektur-Metriken für Kopplung wie der Grad ein- und ausgehender Abhängigkeiten (R1)"

and please add a "z.B." to "Quelltext-bezogene Metriken z.B. Lines-of-Code, (zyklomatische) Komplexität (R1)"

thanx!

2024-06-10 06:16 UTC, gernotstarke requested changes
@mikesperber sorry to be a pita:

you still use the noun. I suggest the following wording:

"Architektur-Metriken für Kopplung wie der Grad ein- und ausgehender Abhängigkeiten (R1)"

and please add a "z.B." to "Quelltext-bezogene Metriken z.B. Lines-of-Code, (zyklomatische) Komplexität (R1)"

and please use the complete term "penetration test" instead of pen-test

thanx!

2024-06-11 06:20 UTC, mikesperber commented
> you still use the noun. I suggest the following wording:
> 
> "Architektur-Metriken für Kopplung wie der Grad ein- und ausgehender Abhängigkeiten (R1)"

I'm not sure I understand the comment (what noun?), but I copied your wording.
 
> and please add a "z.B." to "Quelltext-bezogene Metriken z.B. Lines-of-Code, (zyklomatische) Komplexität (R1)"

Done.
 
> and please use the complete term "penetration test" instead of pen-test

Done.

2024-06-11 07:53 UTC, gernotstarke commented
> I'm not sure I understand the comment (what noun?)

@mikesperber to explain the "nouns": Eingangsabhängigkeit, Ausgangsabhängigkeiten

thanx for updating again...

2024-06-11 09:36 UTC, gernotstarke approved these changes

2024-06-11 09:36 UTC, merged