#464 check and fix minor translation issues
isaqb-org/curriculum-foundation pull request #465
Opened 2024-07-12 18:28 UTC by sippsack

Removed TODO and fixed some translations in headings and typos in text

2024-07-15 13:07 UTC, gernotstarke commented on docs/02-requirements/LZ-02-04.adoc
maybe "understand the Importance of Requirements for Software Architecture" or similar...

2024-07-15 13:09 UTC, gernotstarke requested changes
I suggest some changes, see detailed comments

2024-07-15 13:55 UTC, sippsack commented
Thanks for your suggestions, will work them in shortly

2024-07-15 17:45 UTC, sippsack commented on docs/01-basics/LZ-01-04.adoc
adjusted quite a few other LG titles

2024-07-16 07:18 UTC, gernotstarke commented on docs/01-basics/LZ-01-02.adoc
sorry to be nitpicking. 

* Now we have title and content inconsistent:  In the title we use "Nutzen", in the text you use "Vorteile".
Please change both to  "Nutzen" 

* Grammar: we write "zu unterstützen", "zu erreichen"... but you removed the "zu" from "zu reduzieren". Please add that again

2024-07-16 07:19 UTC, gernotstarke requested changes
one minor issue concerning "Nutzen" and "Vorteile", plus one grammatical issue...

2024-07-16 10:09 UTC, gernotstarke approved these changes
thanx Falk!

2024-07-16 10:10 UTC, merged