#434 updated references, added missing iSAQB glossary etc
isaqb-org/curriculum-foundation pull request #466
Opened 2024-07-22 15:26 UTC by gernotstarke

if one of you could please take a brief look... trivial change.

2024-07-23 17:59 UTC, CodingJenka approved these changes

2024-07-23 18:08 UTC, mahboubagharbi submitted a review, later dismissed

2024-07-24 05:53 UTC, alxlo commented on docs/09-references/00-references.adoc
> +- [[[isaqbglossary,iSAQB Glossary]]] Gernot Starke et. al. iSAQB Glossary of Software Architecture Terminology. Freely available https://leanpub.com/isaqbglossary.
```suggestion
- [[[isaqbglossary,iSAQB Glossary]]] Gernot Starke et. al. iSAQB Glossary of Software Architecture Terminology. Freely available from https://leanpub.com/isaqbglossary or its source repository https://github.com/isaqb-org/glossary/releases
```

2024-07-24 05:55 UTC, alxlo reviewed
I'd rather point to Leanpub AND the Github repo for the glossary, see suggestion.

2024-07-24 08:54 UTC, programming-wolf requested changes
Please fix that one typo, then we can merge this PR 🙂

2024-07-24 08:54 UTC, programming-wolf commented on docs/09-references/00-references.adoc
> +- [[[isaqbdownloads,iSAQB Downloads]]] iSAQB public download site.  https://public.isaqb.org. Contains curriculae and mock-examination.
*curricula (curriculae is wrong, as curriculum is the singular form 🙂 )

2024-07-24 12:32 UTC, programming-wolf commented
Now there are merge conflcits..

2024-07-24 12:46 UTC, merged